ebook_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད་།
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།
  - མཛད་པ་པོ། སྡོམ་བུ་བ་པདྨ་རྣམ་རྒྱལ།
  sku: RDI-SS-09
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: The Light of the Jewel:A Commentary on the Key Points of Jamgon Kongtrul Lodro
      Thaye's Stages of Creation and Completion
    bo: བསྐྱེད་རྫོགས་གནད་བསྡུས་ཀྱི་འགྲེལ་བ་ནོར་བུའི་སྣང་བ།
  collection:
    en: RDI Study Series–  Book 9
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༩
  author:
    en: Authors:Jamgon Kongtrul Lodro Thaye,Pema Namgyal
    bo: པདྨ་རྣམ་རྒྱལ།,འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-09
  category:
    en: Deity Practice
    bo: བསྐྱེད་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-09.epub
  description:
    en: ༄༅། །བོད་དུ་སྤྱིར་མདོ་སྔགས་གཉིས། སྒོས་སུ་གསང་སྔགས་རྡོ་རྗེ་ཐེག་པ། ཡང་སྒོས་རྣལ་འབྱོར་བླ་མེད་ཀྱི་རྒྱུད་ས་དར་རྡོ་དར་གྱིས་གྲུབ་ཐོབ་ཀྱི་ཚང་བརྡོལ།
      དེ་རྣམས་ལས་རྒྱུད་ཀྱི་དགོངས་དོན་རྟོགས་པ་མཐར་ཕྱིན་པའི་བླ་མ་རེ་རེ་བཞིན་གྱིས་མཆོག་དམན་གདུལ་བྱའི་སྐལ་འཚམས་རྒྱུད་དོན་དྲིལ་བའི་མན་ངག་རྩལ་འདོན་མཛདཔས་སྒྲུབ་བརྒྱུད་ཤིང་རྟ་ཆེན་པོ་བརྒྱད་ཅེས་ངོ་མཚར་རྨད་དུ་བྱུང་བའི་བཀའ་སྲོལ་བྱུང་ཡང་བསྟན་པ་འཕེལ་འགྲིབ་དབང་གིས་གདམས་ངག་དེ་དག་གི་རྒྱུན་ཕལ་ཆེར་ནུབ་ཉེར་གྱར་སྐབས།
      སྙིགས་འགྲོའི་དཔལ་མགོན་དམ་པ་རིས་མེད་བསྟན་པའི་བདག་པོ་༧རྗེ་འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས་པའི་སྡེ་མཆོག་གིས་དུས་རབས་བཅུ་དགུ་པར་སྒྲུབ་བརྒྱུད་ཆུ་བོ་གཅིག་འདུས་ཀྱི་ལམ་སྲོལ་སྔོན་མེད་གསར་དུ་གཏོད་པ་ལས་རིས་མེད་གདུལ་བྱར་རྗེས་བརྩེ་ཆུ་འཛིན་ཕུང་པོ་མཁར་འཁྲིགས་དམ་ཆོས་ཆར་རྒྱུན་མཐའ་ཡས་སུ་ཕབ་པའི་ཆོས་ཀྱི་ཡོ་ལང་ལས་བསྐྱེད་རྫོགས་གནད་བསྡུས་ཞེས་པའི་ཆོས་ཚན་འདི་ཉིད་ལའང་སྡོང་བུ་བ་པདྨ་རྣམ་རྒྱལ་གྱིས་འགྲེལ་བ་ནོར་བུའི་སྣང་བ་སྦྱར་བ་ནི་རང་རེ་ཚེ་ཐུང་དབང་རྟུལ་རྒྱུད་སྡེ་རྒྱ་མཚོའི་ལམ་རིམ་པ་གཉིས་ཀྱི་འཇུག་སྒོར་འཇུག་མོས་སྐོམ་པ་ཆུ་འདོད་ཡོད་པ་རྣམས་ལ་རྒྱུད་སྡེའི་སྒོ་བརྒྱ་བདེ་བླག་ཏུ་འབྱེད་པའི་འཕྲུལ་གྱི་ལྡེའུ་མིག་ཏུ་ངེས་སོ།
      །
    bo: ༄༅། །བོད་དུ་སྤྱིར་མདོ་སྔགས་གཉིས། སྒོས་སུ་གསང་སྔགས་རྡོ་རྗེ་ཐེག་པ། ཡང་སྒོས་རྣལ་འབྱོར་བླ་མེད་ཀྱི་རྒྱུད་ས་དར་རྡོ་དར་གྱིས་གྲུབ་ཐོབ་ཀྱི་ཚང་བརྡོལ།
      དེ་རྣམས་ལས་རྒྱུད་ཀྱི་དགོངས་དོན་རྟོགས་པ་མཐར་ཕྱིན་པའི་བླ་མ་རེ་རེ་བཞིན་གྱིས་མཆོག་དམན་གདུལ་བྱའི་སྐལ་འཚམས་རྒྱུད་དོན་དྲིལ་བའི་མན་ངག་རྩལ་འདོན་མཛདཔས་སྒྲུབ་བརྒྱུད་ཤིང་རྟ་ཆེན་པོ་བརྒྱད་ཅེས་ངོ་མཚར་རྨད་དུ་བྱུང་བའི་བཀའ་སྲོལ་བྱུང་ཡང་བསྟན་པ་འཕེལ་འགྲིབ་དབང་གིས་གདམས་ངག་དེ་དག་གི་རྒྱུན་ཕལ་ཆེར་ནུབ་ཉེར་གྱར་སྐབས།
      སྙིགས་འགྲོའི་དཔལ་མགོན་དམ་པ་རིས་མེད་བསྟན་པའི་བདག་པོ་༧རྗེ་འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས་པའི་སྡེ་མཆོག་གིས་དུས་རབས་བཅུ་དགུ་པར་སྒྲུབ་བརྒྱུད་ཆུ་བོ་གཅིག་འདུས་ཀྱི་ལམ་སྲོལ་སྔོན་མེད་གསར་དུ་གཏོད་པ་ལས་རིས་མེད་གདུལ་བྱར་རྗེས་བརྩེ་ཆུ་འཛིན་ཕུང་པོ་མཁར་འཁྲིགས་དམ་ཆོས་ཆར་རྒྱུན་མཐའ་ཡས་སུ་ཕབ་པའི་ཆོས་ཀྱི་ཡོ་ལང་ལས་བསྐྱེད་རྫོགས་གནད་བསྡུས་ཞེས་པའི་ཆོས་ཚན་འདི་ཉིད་ལའང་སྡོང་བུ་བ་པདྨ་རྣམ་རྒྱལ་གྱིས་འགྲེལ་བ་ནོར་བུའི་སྣང་བ་སྦྱར་བ་ནི་རང་རེ་ཚེ་ཐུང་དབང་རྟུལ་རྒྱུད་སྡེ་རྒྱ་མཚོའི་ལམ་རིམ་པ་གཉིས་ཀྱི་འཇུག་སྒོར་འཇུག་མོས་སྐོམ་པ་ཆུ་འདོད་ཡོད་པ་རྣམས་ལ་རྒྱུད་སྡེའི་སྒོ་བརྒྱ་བདེ་བླག་ཏུ་འབྱེད་པའི་འཕྲུལ་གྱི་ལྡེའུ་མིག་ཏུ་ངེས་སོ།
      །
